### ISSUE TITLE
[Bug] Permission denied to ~/.teleserver 

### ISSUE THREAD

**Issue by Dysproz** [Dysproz/teleserver#50]
**Describe the bug**
On logging into teleserver from CLI I get:
```
Traceback (most recent call last):
  File "/home/szymon/.local/bin/teleserver", line 10, in <module>
    sys.exit(teleserver.cli())
  File "/home/szymon/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/szymon/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/szymon/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/szymon/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/szymon/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/szymon/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/szymon/.local/lib/python3.6/site-packages/teleserver/login_cli.py", line 69, in login_in
    os.makedirs('~/.teleserver')
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '~/.teleserver'
```

**To Reproduce**
1. Run `teleserver log in` with valid parameters

**Desktop (please complete the following information):**
 - OS: ubuntu18.04
 - Version 0.0.3

**Comment by Dysproz** [comment]
Fixed in PR #52
